baseURL = "https://stepuptutors.co.uk"
languageCode = "en-uk"
title = "Step Up Tutors"
author = "Steve Tuck"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
copyright = "Step Up Tutors"

theme = "ananke-mod"

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    url = "/"

  [[menu.main]]
    name = "Your First Session"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 2
    url = "/your-first-session"

  [[menu.main]]
    name = "Specific Learning Difficulties"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 3
    url = "/specific-learning-difficulties"

  [[menu.main]]
    name = "Teaching Approaches"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 4
    url = "/teaching-approaches"

  [[menu.main]]
    name = "KS2 SATs"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 5
    url = "/ks2-sats"

  [[menu.main]]
    name = "Contact"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 6
    url = "/contact"


[params]
  featured_image = "/iStock_000006456892_Small.jpg"
  favicon = "/favicon.ico"
  recent_posts_number = 0

  background_color_class = "bg-mid-gray"
  cover_dimming_class = "bg-black-40"
  env = "production" # needed for robots.txt enabled
