baseURL = "https://tuck1s.github.io/stepuptutors-co-uk/"
languageCode = "en-uk"
title = "Step Up Tutors"
author = "Steve Tuck"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
enableRobotsTXT = true
copyright = "Step Up Tutors"

theme = "ananke-mod"

[indexes]
  tag = "tags"
  topic = "topics"

[menu]
  [[menu.main]]
    name = "Home"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 1
    url = "/"

  [[menu.main]]
    name = "Your First Session"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 2
    url = "/your-first-session"

  [[menu.main]]
    name = "Specific Learning Difficulties"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 3
    url = "/specific-learning-difficulties"

  [[menu.main]]
    name = "Teaching Approaches"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 4
    url = "/teaching-approaches"

  [[menu.main]]
    name = "KS2 SATs"
    pre = "<i class='fa fa-home fa-fw'></i>"
    weight = 5
    url = "/ks2-sats"

[params]
  featured_image = "/iStock_000006456892_Small.jpg"
  favicon = "/favicon.ico"
  background_color_class = "bg-mid-gray"
  recent_posts_number = 0
  cover_dimming_class = "bg-black-40"

  # tuck1s additions
  email = "info@stepuptutors.co.uk"
  phone = "02392 250238"

# multiLineDescription = ["one", "two"] in page front matter

